# Generated by Django 4.1.7 on 2023-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
